#!/bin/bash

SEASON="bcrmc7"

echo "Building packs for season $SEASON"

TOP=$(pwd)

STAMP=$(date +%Y-%m-%dT%H%M%S%z)

DATAPACK_FNAME="${SEASON}-datapack_${STAMP}.zip"
RESPACK_FNAME="${SEASON}-resources_${STAMP}.zip"

.venv/bin/beet build

BEET_EXIT=$?

if [[ $BEET_EXIT -ne 0 ]]; then
    echo "!!! beet build exited with non-zero status ${}"
    echo "Aborting."
    exit $BEET_EXIT
fi

echo "-- Building datapack from datapack/"
cd "${TOP}/dist/${SEASON}_data_pack" && zip -FSr "${TOP}/dist/${DATAPACK_FNAME}" .

echo "-- Building resource pack from resources/"
cd "${TOP}/resources" && zip -FSr "${TOP}/dist/${RESPACK_FNAME}" .

echo "-- Symlinking datapack as latest"
ln -sf "${TOP}/dist/${DATAPACK_FNAME}" "${TOP}/dist/${SEASON}-datapack_latest.zip"

echo "-- Symlinking resource pack as latest"
ln -sf "${TOP}/dist/${RESPACK_FNAME}" "${TOP}/dist/${SEASON}-resources_latest.zip"
