#!/bin/bash

function usage {
    echo "usage: ln-data WORLD_NAME"
}

[[ $# -ne 1 ]] && usage && exit 1

WORLD="$1"
WORLD=$(echo "${WORLD}" | tr '.' '_')
LN_TARGET="$HOME/.minecraft/saves/$WORLD/datapacks/LINKED-bcrmc-datapack"

rm -f "$LN_TARGET"
ln -s "$(pwd)/dist/bcrmc_data_pack" "$LN_TARGET"
