#!/bin/bash

function usage {
    echo "usage: ln-data WORLD_NAME"
}

[[ $# -ne 1 ]] && usage && exit 1

WORLD="$1"
LN_TARGET="$HOME/.minecraft/saves/$WORLD/datapacks/LINKED-bcrmc-datapack"

rm "$LN_TARGET"
ln -s "$(pwd)/dist/bcrmc7_data_pack" "$LN_TARGET"
